name: Run e2e tests on project

on:
    push:
      branches:
        - "main"
    pull_request:

jobs:
  run-playwright:
    name: Run playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
      - name: Install dependencies
        run: |
            npm ci
      - name: Install playwright browsers
        run: |
            npx playwright install --with-deps chromium webkit firefox
      - name: Run tests
        id: run-tests
        run: |
            xvfb-run --auto-servernum -- npm run test-e2e
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: ${{ !cancelled() && failure() && steps.run-tests.conclusion == 'failure' }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 2
